services:
  api:
    image: frankefelipe5/calmail:latest
    networks:
      - api_net
    env_file: ".env"

  auth-with-keycloak:
    image: quay.io/keycloak/keycloak:26.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${PSQL_HOST}:${PSQL_PORT}/${PSQL_DB}
      KC_DB_USERNAME: ${PSQL_USR}
      KC_DB_PASSWORD: ${PSQL_PASS}
      KC_HTTP_PORT: ${KC_HTTP_PORT}
      KC_HTTPS_PORT: ${KC_HTTPS_PORT}
      KC_PROXY_HEADERS: ${KC_PROXY_HEADERS}
      KC_HTTP_ENABLED: "true"
    networks:
      - api_net
    env_file: ".env"
    command: ["start-dev"]

  nginx:
    image: frankefelipe5/calmai-nginx:latest
    env_file: ".env"
    ports:
      - "80:80"
    networks:
      - api_net

networks:
  api_net:
    driver: bridge