services:
  api:
    image: frankefelipe5/calmail
    networks:
      - api_net
    env_file: ".env"
  auth-with-keycloak:
    image: quay.io/keycloak/keycloak:26.1
    hostname: auth-with-keycloak
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_LOG_LEVEL: info
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - api_net
    env_file: ".env"
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]

  nginx:
    image: frankefelipe5/calmai-nginx
    build:
      args:
        - ENV=${ACTIVE_PROFILE}
    ports:
      - "80:80"
    networks:
      - api_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - auth-with-keycloak

networks:
  api_net:
    driver: bridge