CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS ai_response (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    request JSON NOT NULL,
    response_text VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP WITH TIME NOT NULL DEFAULT NOW()
);